// Build step: point the native shims at whatever platform packages npm installed on this machine
// (@duckdb/node-bindings-<platform>, nodejs-polars-<platform>). Writes src/native/platform.gen.ts and tsconfig.json.
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const nm = "node_modules";
const pick = (dir: string, prefix: string) => {
  const hit = readdirSync(dir).find(d => d.startsWith(prefix) && !d.endsWith("bindings")); // skip the JS loader package itself
  if (!hit) throw new Error(`no ${prefix}* package in ${dir} — run npm install on this platform`);
  return join(dir, hit);
};

const duck = pick(join(nm, "@duckdb"), "node-bindings-");
const duckFiles = readdirSync(duck);
const duckLib = duckFiles.find(f => /^(lib)?duckdb\.(so|dylib|dll)$/.test(f));
if (!duckLib || !duckFiles.includes("duckdb.node")) throw new Error(`unexpected layout in ${duck}: ${duckFiles}`);

const polars = pick(nm, "nodejs-polars-");
const polarsNode = readdirSync(polars).find(f => f.endsWith(".node"));
if (!polarsNode) throw new Error(`no .node file in ${polars}`);

const rel = (p: string) => "../../" + p; // from src/native/
writeFileSync("src/native/platform.gen.ts", `// generated by scripts/gen-native.ts for ${process.platform}-${process.arch}; do not edit
import duckPkg from "${rel(duck)}/package.json";
import duckNode from "${rel(duck)}/duckdb.node" with { type: "file" };
import duckLib from "${rel(duck)}/${duckLib}" with { type: "file" };
import polarsPkg from "${rel(polars)}/package.json";
import polarsNode from "${rel(polars)}/${polarsNode}" with { type: "file" };
export const duckdb = { version: duckPkg.version, node: duckNode, lib: duckLib, libName: ${JSON.stringify(duckLib)} };
export const polarsNative = { version: polarsPkg.version, node: polarsNode };
`);

// nodejs-polars require()s its platform package by name; alias that name to our shim
const polarsName = polars.slice(nm.length + 1);
writeFileSync("tsconfig.json", JSON.stringify({
  compilerOptions: { paths: {
    "@duckdb/node-bindings": ["./src/native/duckdb-binding.ts"],
    [polarsName]: ["./src/native/polars-binding.ts"],
  } },
}, null, 2) + "\n");

if (!existsSync("src/native/platform.gen.ts")) throw new Error("write failed");
console.log(`native: ${duck} (${duckLib}), ${polars} (${polarsNode})`);
